### ISSUE TITLE
Правілы канвертацыі ў асобным json файле

### ISSUE THREAD

**Issue by pikoshyk** [GooseOb/taraskevizatar#1]
Хочацца зрабіць тарашкевізатар для iOS/Swift у якасці бібліятэкі пад ліцэнзіяй MIT. Але падтрымліваць абнаўленне правіл будзе мне цяжкавата. То вырашыў спытаць, ці можна у вас ё жаданне вынесці спіс усіх правіл канвертацыі з src/js/srcs.js ў нейкі асобны json файл і абнаўляць ужо яго, каб распрацоўшчыкі з іншых платорм маглі аднойчы зрабіўшы канвертар толькі абнаўляць гэты json?

**Comment by GooseOb** [comment]
Магу ў працэсе зборкі генэраваць json'ы і складаць у асобную папку, пасуе такое рашэньне?

Прапановы па зьменах у "слоўніку" прапаную ў іш'ю кідаць

**Comment by pikoshyk** [comment]
Так, было б вельмі добра мець спасылку на правілы ў асабістым json файле, каб не цягнуць яго ў свой рэпазіторый, бо вы, я заўважыў, працуеце над імі, і час ад часу абнаўляеце.

**Comment by GooseOb** [comment]
То пра 2 галоўныя файлы напісана ў readme праекту, яны ў папцы json ляжаць (трэ raw націснуць на файле каб чысты json паказала). Але не зусім ўпэўнены, што рухавік рэгулярных выразаў у swift падтрымлівае усе канструкцыі, што я выкарыстоўваў. Калі будуць якіясь памылкі, то кідай сюды, паспрабую выправіць

**Comment by GooseOb** [comment]
Вітаю, лёгіка тарашкевізацыі і слоўнік разам з json'амі будуць выдалены з гэтага рэпазыторыю. Калі гэта яшчэ для вас актуальна, рэкамэндую цяпер браць json'ы [адсюль](https://github.com/GooseOb/taraskevizer/tree/main/json)
А таксама новыя іш'ю кідаць у той рэпо
