### ISSUE TITLE
"катар"->"катэр", "кратар"->"кратэр", "штэпсель"->"штэпсэль", "бульдозер"->"бульдозэр", "спартсмен"->"спартсмэн" ды іншыя

### ISSUE THREAD

**Issue by ssvb** [GooseOb/taraskevizatar#10]
[Разьдзел 3. ПРАВАПІС Э](https://knihi.com/storage/pravapis2005.html#texth2_3)

> барэль, гатэль, грыфэль, дросэль, кабэль, камізэлька, мадмуазэль, ніпэль, пудэль, штрыфэль, штэпсэль; Базэль, Гэндэль, Мозэль;

> бармэн, дзэн, кузэн, люмпэн, мэтрапалітэн, скансэн, спартсмэн, фэн; Армэн, Сэн-Жэрмэн, Шапэн[[9]](https://knihi.com/storage/pravapis2005.html#ftn9);

> абанэнт, аргумэнт, брызэнт, дакумэнт, камплімэнт, парлямэнт, пэргамэнт (побач з пэргамін), рэглямэнт, сакрамэнт, тастамэнт; Вінцэнт, Сэнт-Вінсэнт; але: момант;

> абвэр, бульдозэр, буфэр, бэльвэдэр, вінчэстэр, грэйдэр, дызайнэр, кампостэр, катэр, кратэр, лідэр, обэр-, піянэр, рэвалюцыянэр, сканэр, трэнэр, шофэр; Картэр, Ма́нчэстэр, Ошэр, Роджэр, Ройтэр, Фішэр;

> дэбэт, катэт, партаманэт, унівэрсытэт, эпітэт; Са́мэрсэт;

**Comment by ssvb** [comment]
Мне цікава, ці шмат яшчэ падобных словаў, акрамя тых прыкладаў з [БКП-2005](https://knihi.com/storage/pravapis2005.html)? Можа мае сэнс неяк аўтаматычна прааналізаваць be-tarask вікіпедыю для збору такой інфармацыі?

**Comment by ssvb** [comment]
Дарэчы, са словам "катар" зрабілі нейкае дзікунства. У наркамаўцы да [рэформы 2008 году](https://be-tarask.wikipedia.org/wiki/%D0%9F%D1%80%D0%B0%D0%B2%D1%96%D0%BB%D1%8B_%D0%B1%D0%B5%D0%BB%D0%B0%D1%80%D1%83%D1%81%D0%BA%D0%B0%D0%B9_%D0%B0%D1%80%D1%82%D0%B0%D0%B3%D1%80%D0%B0%D1%84%D1%96%D1%96_%D1%96_%D0%BF%D1%83%D0%BD%D0%BA%D1%82%D1%83%D0%B0%D1%86%D1%8B%D1%96_(2008)) былі асобныя словы ["катар"](https://www.skarnik.by/tsbm/32535) і ["катэр"](https://www.skarnik.by/tsbm/32581). Таксама ["Катар"](https://be-tarask.wikipedia.org/wiki/%D0%9A%D0%B0%D1%82%D0%B0%D1%80) - назва краіны. Пасьля рэформы 2008 году застаўся толькі "катар", адзіны на ўсіх.

**Comment by GooseOb** [comment]
Дзякуй, дададзена
