### ISSUE TITLE
TypeError caused by certain input words

### ISSUE THREAD

**Issue by somerandomguyontheweb** [GooseOb/taraskevizatar#13]
Hi, just wanted to let you know that the converter fails when the input text contains certain wordforms, most prominently *кісларода* and Lithuanian toponyms, such as *Акмяне*, *Анікшчэй*, *Варэны*, *Эжарэліс*, etc. The web interface says:
```
TypeError: a is undefined
```

I haven't debugged the issue, but from cursory glance it appears to be somehow related to whitespaces and lookahead groups in the regexes in `core/dict.ts`, e.g.: `/кісларода /`, `/акмяне(?= )/`.

Thanks

**Comment by GooseOb** [comment]
You're right, thanks. Fixed
