### ISSUE TITLE
Канвертацыя "не"->"ня" працуе не з усімі словазлучэньнямі

### ISSUE THREAD

**Issue by ssvb** [GooseOb/taraskevizatar#14]
Напрыклад, у самім тэксьце https://knihi.com/storage/pravapis2005.html можна знайсьці наступныя словазлучэньні, якія пішуцца з "ня":
```
ня беглы
ня пішацца
ня пішуцца
ня блытаць
```
Але тарашкевізатар не выпраўляе "не" на "ня" ў гэтых выпадках. І можна знайсьці больш прыкладаў у іншых кнігах тарашкевіцай. Патрэбны "націскатар" для расстаноўкі націскаў і канчатковага вырашэньня гэтай праблемы ў прынцыпе?

**Comment by GooseOb** [comment]
Дзякуй, дадаў гэтыя выпадкі

Наконт канчатковага рашэньня праблемы ня ведаю пакуль, можа быць можна базу словаў з націскам на першы склад загрузіць
