### ISSUE TITLE
Виділити у окрему бібліотеку

### ISSUE THREAD

**Issue by noomorph** [GooseOb/taraskevizatar#16]
Вітаю! Дуже цікавий проєкт, але я от думаю, як би його зінтегрувати з екосистемою https://unifiedjs.com 

От приклад: https://github.com/retextjs/retext-simplify

Просто думаю, що можна було б парсити текст за допомогою існуючого retextjs, а токени (слова) передавати до taraskevizatar. Фактично, якщо б виокремити функцію, що приймає слово одним правописом і конвертує у інший, то це 90% задачі.

Так, наприклад, це би дозволило генерувати документацію одночасно і наркомівкою, і тарашкевицею на сайтах, що базуються на Markdown-контенті та інших (unifiedjs не має обмеження щодо формату - лише питання наявності парсера, а там підтримується широкий спектр форматів, насправді). Чи це могло б вас зацікавити, хоча б гіпотетично?

**Comment by GooseOb** [comment]
Зараз працую над гэтым

**Comment by GooseOb** [comment]
Гатова

[npm](https://www.npmjs.com/package/taraskevizer)
[github repo](https://github.com/GooseOb/taraskevizer)

**Comment by noomorph** [comment]
Дякую, маю надію незабаром спробувати у проєкті.

**Comment by noomorph** [comment]
@Zmicier21, dobra věst. Imajemo šans stvoriti novu kolonu v tabelě za taraškevicu. Možlivo, jesenju budemo poprobovati.
