### ISSUE TITLE
Словы "Альцгеймер" і "Альхеймер" абодва канвертуюцца ў "Alchiejmier"

### ISSUE THREAD

**Issue by ssvb** [GooseOb/taraskevizatar#17]
Адным з пажаданых патрабаванняў да стандартаў раманізацыі з'яўляецца "reversibility". Стандарт ["The Roman alphabet transliteration of Belarusian geographical names"](https://unstats.un.org/unsd/geoinfo/UNGEGN/docs/10th-uncsgn-docs/crp/E_CONF.101_CRP2_The%20Roman%20alphabet%20transliteration.pdf) згадвае пра "reversibility". Але, відаць, у Беларусі няма населеных пунктаў са спалучэннем літар "цг" у назве.

Не ведаю, ці ёсць патрэба нешта мяняць. Можа проста заўсёды канвертаваць "цг" у "cg"?

**Comment by GooseOb** [comment]
Але ў арыгінале там Alzheimer (дрч чытаецца як альцгаймэр, бо зь нямецкай). Ня думаю што варта ўласныя назвы пры лацінізацыі пісаць як у арыгінале, бо ўсіх не запішаш і яны не такія частыя

**Comment by ssvb** [comment]
Я толькі маю на ўвазе, што было б пажаданым пазбегнуць страты інфармацыі падчас канвертацыі з кірыліцы ў лацінку і назад. Спалучэнне літар "ch" у лацінцы канвертуецца або ў "х", або ў "цг" і гэта не ёсць добра.

**Comment by ssvb** [comment]
Вікіслоўнік мае пэўныя патрабаванні наконт транслітэрацыі/раманізацыі: https://en.wiktionary.org/wiki/Wiktionary:Transliteration_and_romanization

> Criteria for romanization systems
>
> A transliteration system is a balance between several, often contradictory, goals. Different systems may be better suited for different purposes, including lexicography, linguistic study, geographic naming, bibliographic cataloguing, diplomatic communication, etc., based on how well they meet particular goals.
>
> Guidelines for transliteration systems:
>
> United Nations Group of Experts on Geographical Names:
> * Reversible
> * Simple and clear-cut
>     * Table and notes to be sufficient; not requiring dictionaries, etc.
>     * Not allowing for variations in the romanization
> * Easy to write, read, and memorize, as well as store electronically
>     * Minimizing diacritics, unusual character sequences, etc.
>     * Systematically representing phonology

Цяпер выкарыстоўваецца наступная сістэма транслітэрацыі для беларускай мовы: https://en.wiktionary.org/wiki/Wiktionary:Belarusian_transliteration

Прыклад для беларускага слова ["глухі"](https://en.wiktionary.org/wiki/%D0%B3%D0%BB%D1%83%D1%85%D1%96).

Я думаю, што было б добра прапанаваць замену іхняй сістэмы транслітэрацыі для беларускай мовы на стандартную беларускую лацінку.
