### ISSUE TITLE
Трэці апостраф (U+02BC)

### ISSUE THREAD

**Issue by ssvb** [GooseOb/taraskevizatar#4]
Вынік канвертацыі: "зʼява з’ява з'ява" -> "зʼява зьява зьява". Дарэчы, менавіта U+02BC ужываецца для беларускіх і ўкраінскіх даменных імёнаў у інтэрнэце:
* [Ангельская вікіпедыя](https://en.wikipedia.org/wiki/Apostrophe#Unicode)
* [Украінская вікіпедыя](https://uk.wikipedia.org/wiki/%D0%90%D0%BF%D0%BE%D1%81%D1%82%D1%80%D0%BE%D1%84#%D0%9A%D0%BE%D0%B4%D1%83%D0%B2%D0%B0%D0%BD%D0%BD%D1%8F_%D0%B0%D0%BF%D0%BE%D1%81%D1%82%D1%80%D0%BE%D1%84%D0%B0)
* [Спраўдзіць наяўнасць даменнага імені для рэгістрацыі ў зоне .бел](https://whois.cctld.by/#/whois)

**Comment by GooseOb** [comment]
Выпраўлена
