### ISSUE TITLE
Спроба канвэртацыі слова "пераддзвер'е" ламае сэрвіс

### ISSUE THREAD

**Issue by ssvb** [GooseOb/taraskevizatar#6]

**Comment by ssvb** [comment]
І таксама "дыэтаноламін"

**Comment by GooseOb** [comment]
Выпраўлена

**Comment by ssvb** [comment]
Дзякую! Але ёсць яшчэ шмат іншых слоў. Напрыклад, "варэнне". Я б параіў дадаваць рэгрэсіўныя тэсты для кожнага з выпраўленых слоў. І такім чынам гарантаваць, што прынамсі гэтыя праблемы ніколі не вернуцца.

**Comment by ssvb** [comment]
> Я б параіў дадаваць рэгрэсіўныя тэсты для кожнага з выпраўленых слоў.

Я маю на ўвазе https://github.com/GooseOb/taraskevizatar/blob/main/api/test/app.e2e-spec.ts
