### ISSUE TITLE
Групы словаў з https://github.com/Belarus/GrammarDB выклікаюць праблемы канверсіі

### ISSUE THREAD

**Issue by ssvb** [GooseOb/taraskevizatar#8]
Канверсія працуе нашмат хутчэй, калі словы канверсуюцца не паасобку, а вялікімі групамі праз коску. Некаторыя з такіх груп выклікаюць праблемы канверсіі нават калі праблемныя словы з #7 адфільтраваны. Спіс:
 ```
Індуры,Інды,Індый,Індыч,Індычам
Самары,Самарый,Самарыю,Самарыя,Самарыяй
Франусіну,Францый,Францысак,Францыск,Францыска
```
Магчыма гэта таму, што імёны і назвы краінаў у гэтым спісе пачынаюцца з вялікай літары?

**Comment by GooseOb** [comment]
Выпраўлена
