### ISSUE TITLE
Канвертацыя слова "везці" не дадае мяккі знак (адрозніваецца ад baltoslav)

### ISSUE THREAD

**Issue by ssvb** [GooseOb/taraskevizatar#9]
Артыкулы на https://be-tarask.wikipedia.org/ ужываюць слова "везьці". Але я сам не эксперт.

**Comment by ssvb** [comment]
"абанемент" -> "абанемэнт", baltoslav: "абанемэнт", wikipedia "абанэмэнт", dobrapis: "абанэмэнт".
"бензін" -> "бензін", baltoslav: "бэнзын", wikipedia:"бэнзін", dobrapis: "бэнзін"
"апельсін" -> "апельсін", wikipedia: "апэльсін", dobrapis: "апэльсін"

**Comment by GooseOb** [comment]
Выпраўлена
